

//Carlos Emanuel Sancir Reyes
//carnet 202201131

package practica1_buena;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanci
 */
public class AdminitradordeCursos extends javax.swing.JFrame {

    /**
     * Creates new form AdminitradordeCursos
     */
    ArrayList<Profesor> Profe;
    ArrayList<Cursos> curso;
    ArrayList<Alumnos> Alumno;
    ArrayList<Actividades> actividad;
    ArrayList<Alumnos> actividadauxiliar = new ArrayList<Alumnos>();
    int indice;
    String indiceClase;
    public AdminitradordeCursos(ArrayList<Profesor> Profe,ArrayList<Cursos> curso,ArrayList<Alumnos> Alumno, int indice,String indiceClase,ArrayList<Actividades> actividad) {
        this.Profe = Profe;
        this.curso = curso;
        this.Alumno = Alumno;
        this.indice=indice;
        this.indiceClase=indiceClase;
        this.actividad = actividad;
        initComponents();
        //cargarAutomatica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCargaAlumnos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnMejor = new javax.swing.JButton();
        btnPeor = new javax.swing.JButton();
        Acumulado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtDescripcion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPonderacion = new javax.swing.JTextField();
        btncrear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        rutaCursos = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Gua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Acciones"
            }
        ));
        jScrollPane1.setViewportView(tablaAlumnos);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Ponderacion", "Promedio"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Listado Alumnos");

        jLabel2.setText("Actividades");

        btnCargaAlumnos.setText("Carga Masiva Alumnos");
        btnCargaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaAlumnosActionPerformed(evt);
            }
        });

        jLabel3.setText("Reportes");

        btnMejor.setText("Top 5- Estudiantes con Mejor Rendimiento");

        btnPeor.setText("Top 5- Estudiantes con Peor Rendimiento");
        btnPeor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeorActionPerformed(evt);
            }
        });

        Acumulado.setText("Acumulado: ");

        jLabel4.setText("Crear Actividad");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Descripcion:");

        jLabel7.setText("Ponderacion:");

        jLabel8.setText("Notas:");

        btncrear.setText("Crear Actividad");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refrescar Tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Gua.setText("Guardar Tabla");
        Gua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnPeor, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(218, 218, 218))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rutaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Acumulado)
                                .addGap(163, 163, 163))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(btnCargaAlumnos))
                                .addGap(30, 30, 30)
                                .addComponent(Gua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(84, 84, 84)))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMejor, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPonderacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(439, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Acumulado)
                    .addComponent(rutaCursos))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnCargaAlumnos)
                    .addComponent(Gua, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btnMejor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPeor)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPonderacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncrear)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(279, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(130, 130, 130)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeorActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ventanas ventana = new ventanas();
        ventana.ModuloProfesores(Profe, curso, Alumno, indice,actividad);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void leer(String ir) {
        //String csvFile = "C:\\Users\\sanci\\Desktop\\pr\\IPC1_2S2023_Proyecto1_202201131\\Practica1_buena\\Archivos\\PRUEVA.csv"; // Reemplaza con la ruta de tu archivo CSV
        String csvFile = ir; // Reemplaza con la ruta de tu archivo CSV
        String[] data = null;
        List<Alumnos> personas = new ArrayList<>();

        try (BufferedReader reader = new BufferedReader(new FileReader(csvFile))) {
            String line;
            boolean firstLine = true; // Para ignorar la primera línea (encabezados)

            while ((line = reader.readLine()) != null) {
                if (firstLine) {
                    firstLine = false;
                    continue; // Saltar la primera línea
                }
                System.out.println("a");
                String[] parts = line.split(";");
                // parts = line.split(",");

                if (parts.length == 1) {
                    System.out.println("a");

                    
                    String Codigo = parts[0].trim();
                    
                    Alumnos persona = new Alumnos(Codigo);
                    personas.add(persona);
                    System.out.println("Nombre: " + personas.get(0).getNombre() + ", Edad: " + persona.getApellido() + ", Ciudad: " + persona.getCodigo());
                    System.out.println("a");
                }
            }
            
        } catch (FileNotFoundException e ){

            e.printStackTrace();
            System.out.println("Archivo no encontrado");
            JOptionPane.showMessageDialog(null, "Archivo no encontrado ingrese la direcion \n"
                    + "ejemplo C:\\Users\\sanci\\Desktop\\pr\\IPC1_2S2023_Proyecto1_202201131\\Practica1_buena\\Archivos\\PRUEVA.csv ");
        } catch (Exception e) {
            System.out.println("Archivo no encontrado");
            JOptionPane.showMessageDialog(null, "Archivo no encontrado ingrese la direcion \n"
                    + "ejemplo C:\\Users\\sanci\\Desktop\\pr\\IPC1_2S2023_Proyecto1_202201131\\Practica1_buena\\Archivos\\PRUEVA.csv ");
        }
        // Ahora, el ArrayList "personas" contiene objetos Persona con los datos del CSV.
            for (Alumnos persona : personas) {
                System.out.println("Nombre: " + persona.getNombre() + ", Edad: " + persona.getApellido() + ", Ciudad: " + persona.getCodigo());
            }
            for (int i = 0; i < Alumno.size(); i++) {
                for (int j = 0; j < personas.size(); j++) {
                    if(personas.get(j).getCodigo().equals(Alumno.get(i).getCodigo())){
                        String codigo = Alumno.get(i).getCodigo();
                        String nombre = Alumno.get(i).getNombre();
                        String Apellido = Alumno.get(i).getApellido();
                        actividadauxiliar.add(new Alumnos(codigo, nombre, Apellido));
                        
                    }
                }
            }
            //Profe = (ArrayList<Profesor>) personas;

    }
    
    private void btnCargaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaAlumnosActionPerformed
        GuardarAlumnos();
        String rutaArchivo = null;
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Texto (*.txt)", "txt");
        fileChooser.setFileFilter(filter);
        int seleccion = fileChooser.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Obtiene la ruta del archivo seleccionado
            rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();

            // Haz lo que necesites con la ruta del archivo
            System.out.println("Ruta del archivo seleccionado: " + rutaArchivo);
        } else {
            System.out.println("El usuario canceló la selección.");
        }
        leer(rutaArchivo);
            cargarAutomatica();
        /*try {
            String ir = rutaCursos.getText();
            leer(ir);
            cargarAutomatica();
        cargarAutomatica();
        } catch (Exception e) {
            System.out.println("No encontado");
        }*/
    }//GEN-LAST:event_btnCargaAlumnosActionPerformed

    public void GuardarAlumnos(){
        
            int indiceCur = Integer.parseInt(indiceClase);
            
            curso.get(indiceCur).setEstudiante(actividadauxiliar);
            
        
    
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         int indiceCur = Integer.parseInt(indiceClase);
         
         
        
        actividadauxiliar.addAll(curso.get(indiceCur).getEstudiante());
        System.out.println(curso.get(indiceCur).getEstudiante().size());
        System.out.println(actividadauxiliar.size());
        cargarAutomatica();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuaActionPerformed
       GuardarAlumnos();
    }//GEN-LAST:event_GuaActionPerformed

    public void cargarAutomatica() {
        DefaultTableModel modelo = new DefaultTableModel();

        ArrayList<Object> nombrecolumna = new ArrayList<Object>();
        nombrecolumna.add("Codigo");
        nombrecolumna.add("Nombre");
        nombrecolumna.add("Apellido");
        nombrecolumna.add("Informacion");
        
        for (Object columna : nombrecolumna) {
            modelo.addColumn(columna);
        }
        int fila =tablaAlumnos.getRowCount();

        this.tablaAlumnos.setModel(modelo);
        ArrayList<Object[]> datos = new ArrayList<Object[]>();
        for (int i = 0; i < actividadauxiliar.size(); i++) {
            String Codigo = (actividadauxiliar.get(i).getCodigo());
          
            String nombre = (actividadauxiliar.get(i).getNombre());
            String Apellido = (actividadauxiliar.get(i).getApellido());
            
            datos.add(new Object[]{Codigo, nombre, Apellido,  "Informacion"});
            System.out.println(datos);

        }

        for (Object[] Maestros : datos) {
            modelo.addRow(Maestros);
        }
        tablaAlumnos.setModel(modelo);
        
        int aa = Integer.parseInt(indiceClase);
        String numeroAlumnos = String.valueOf(actividadauxiliar.size());
                
        curso.get(aa).setAlumnos(numeroAlumnos);
        System.out.println(curso.get(aa).getAlumnos()+"   dd");
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acumulado;
    private javax.swing.JButton Gua;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JButton btnCargaAlumnos;
    private javax.swing.JButton btnMejor;
    private javax.swing.JButton btnPeor;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField rutaCursos;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPonderacion;
    // End of variables declaration//GEN-END:variables
}
